resources:
- name: some-git-repo
  type: git
  source:
    uri: https://github.com/cf-container-networking/cf-concourse

jobs:
- name: test
  plan:
  - get: some-git-repo
  - task: say-hello
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: alpine}
      run:
        path: echo
        args: ["Hello!"]
